[MM-46]: Updated the message for exporting channels
Brightscout/mattermost-plugin-channel-export pull request #1
Opened 2024-08-21 09:50 UTC by Kshitij-Katiyar

#### Summary
Updated the messages received while exporting different types of channels

### Screenshots
#### Existing
![Screenshot from 2024-08-14 09-19-55](https://github.com/user-attachments/assets/8a6485e0-7102-49d3-8667-cb6abc26524e)
![Screenshot from 2024-08-14 09-05-19](https://github.com/user-attachments/assets/d43555a6-fd68-48ce-b0d2-7aae2e42209e)
![Screenshot from 2024-08-21 14-16-56](https://github.com/user-attachments/assets/be9e99a4-730e-47ec-a16f-9de655ff2d7f)
![Screenshot from 2024-08-21 14-17-40](https://github.com/user-attachments/assets/2aab5978-dffe-421b-8429-8f7f8bf6365c)

#### Updated
![Screenshot from 2024-08-14 09-06-30](https://github.com/user-attachments/assets/97ce7845-f390-454a-ae17-17108755e297)
![Screenshot from 2024-08-21 14-16-20](https://github.com/user-attachments/assets/0ceae8aa-a12f-4ca3-87ab-2b3b39bbb6a8)
![Screenshot from 2024-08-21 15-18-46](https://github.com/user-attachments/assets/278251ca-3929-48fa-9c4d-0cd1490e5736)
![Screenshot from 2024-08-14 09-05-51](https://github.com/user-attachments/assets/661d92e0-c7cc-42fa-9c0d-19b36dd93c27)

2024-08-21 09:53 UTC, raghavaggarwal2308 commented
@Kshitij-Katiyar In `Exporting GM channel ~ID`. Shouldn't "~ID" be a link?

2024-08-21 09:55 UTC, Kshitij-Katiyar commented
> @Kshitij-Katiyar In `Exporting GM channel ~ID`. Shouldn't "~ID" be a link?

@raghavaggarwal2308 This Can be a link, but not much needed as the given message is received in the GM channel only, but can be made a link to maintain the consistency. Should we?

2024-08-21 09:57 UTC, raghavaggarwal2308 commented
> > @Kshitij-Katiyar In `Exporting GM channel ~ID`. Shouldn't "~ID" be a link?
> 
> @raghavaggarwal2308 This Can be a link, but not much needed as the given message is received in the GM channel only, but can be made a link to maintain the consistency. Should we?

Yes, I think we should

2024-08-21 11:05 UTC, Kshitij-Katiyar commented
> > > @Kshitij-Katiyar In `Exporting GM channel ~ID`. Shouldn't "~ID" be a link?
> > 
> > 
> > @raghavaggarwal2308 This Can be a link, but not much needed as the given message is received in the GM channel only, but can be made a link to maintain the consistency. Should we?
> 
> Yes, I think we should. Just for consistency

@raghavaggarwal2308 We have implemented your suggestions and updated the screenshot accordingly. Please have a look

2024-08-26 09:39 UTC, raghavaggarwal2308 requested changes

2024-08-26 09:39 UTC, raghavaggarwal2308 commented on server/command_hooks.go
> +				"GM channel ID", args.ChannelId, "User ID", args.UserId, "Error", err)
```suggestion
			p.client.Log.Error("error occurred while getting the details of team for the channel.", "GMChannelID", args.ChannelId, "TeamID", args.TeamId, "Error", err)
```

2024-08-26 09:39 UTC, raghavaggarwal2308 commented on server/command_hooks.go
> +			}
Having this link is not a must so we can just log the error and continue with our functionality without a link

2024-08-26 11:37 UTC, raghavaggarwal2308 approved these changes

2024-08-27 06:47 UTC, raghavaggarwal2308 approved these changes

2024-08-27 06:47 UTC, raghavaggarwal2308 commented on server/command_hooks.go
> +		team, appErr := p.API.GetTeam(args.TeamId)
use p.client

2024-08-27 07:49 UTC, raghavaggarwal2308 commented on server/command_hooks.go
> +		team, appErr := p.API.GetTeam(args.TeamId)
discussed

2024-08-27 07:50 UTC, Kshitij-Katiyar commented
Created a PR with all the changes on mattermost repo, hence closing this one.

2024-08-27 07:50 UTC, closed without merging