[MM-819]: Added testcases for multiple functions in command_hooks.go file
Brightscout/mattermost-plugin-channel-export pull request #3
Opened 2024-09-30 12:27 UTC by Kshitij-Katiyar

### Summary
Added testcases for multiple functions in command_hooks.go file

2024-09-30 18:27 UTC, raghavaggarwal2308 requested changes

2024-09-30 18:27 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
There is a lot of code repetition in this file. Use a loop to minimize that. Like we do in other plugins

2024-10-03 12:13 UTC, raghavaggarwal2308 requested changes

2024-10-03 12:13 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +		mockAPI := pluginapi.CustomWrapper(mockChannel, mockFile, mockLog, mockPost, mockSlashCommand, mockUser, mockSystem, mockConfiguration, mockCluster)
Can create a common function for this

2024-10-03 12:13 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +			plugin, _ := setupPlugin(t, mockAPI, time.Now())
run api.assertExpectations

2024-10-03 12:13 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +			plugin, _ := setupPlugin(t, mockAPI, time.Now())
Also, what is the second return param here

2024-10-03 12:13 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +			expectedExportPermission: false,
can remove, check everywhere

2024-10-03 12:13 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +				mockUser.EXPECT().HasPermissionToChannel("userID", "chanelID", model.PermissionManageChannelRoles).Return(false)
```suggestion
				mockUser.EXPECT().HasPermissionToChannel("mockUserID", "mockChanelID", model.PermissionManageChannelRoles).Return(false)
```
Update everywhere

2024-10-04 06:11 UTC, Kshitij-Katiyar commented on server/command_hooks_test.go
> +			plugin, _ := setupPlugin(t, mockAPI, time.Now())
`func setupPlugin(t *testing.T, mockAPI *pluginapi.Wrapper, now time.Time) (*Plugin, *plugin.Context)`

It is plugin context but it is not used in our testcases

2024-10-04 12:52 UTC, raghavaggarwal2308 requested changes

2024-10-04 12:52 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +		setupMocks               func(mockUser *mock_pluginapi.MockUser, mockSystem *mock_pluginapi.MockSystem, mockConfiguration *mock_pluginapi.MockConfiguration)
I don't see the mockSystem and mockConfiguration param being used anywhere

2024-10-04 12:52 UTC, raghavaggarwal2308 commented on server/command_hooks_test.go
> +		mockCluster.EXPECT().NewMutex(gomock.Eq(KeyClusterMutex)).Return(pluginapi.NewClusterMutexMock(), nil)
can use setup func

2024-10-07 09:06 UTC, raghavaggarwal2308 approved these changes

2024-10-07 10:01 UTC, Kshitij-Katiyar commented
Created a PR with all these changes on MM remote hence closing this one

2024-10-07 10:01 UTC, closed without merging